modules/test_plan/urls.py
from django.urls import path, re_path
from . import views
from modules.test_plan.views import PlanListView, PlanDetailView, DashboardView, PlanNewView, PlanUpdateView

urlpatterns = [
    path('', DashboardView.as_view(), name='index'),
    path('test_plan_new/',  PlanNewView.as_view(), name='test_plan_new'),
    path('test_plan_list/', PlanListView.as_view(), name='test_plan_list'),
    re_path(r'^test_plan_view/(?P<pk>\d+)$', PlanDetailView.as_view(), name='test_plan_view'),
    re_path(r'^test_plan_edit/(?P<pk>\d+)$', PlanUpdateView.as_view(), name='test_plan_edit'),
    ]

tester/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('modules.test_plan.urls')),
    path('', include('modules.test_case.urls')),
    path('', include('modules.tag.urls')),
    path('', include('modules.profile.urls')),
    path('profile/', include('django.contrib.auth.urls')),
    ]

modules/test_plan/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.urls import reverse


class TestPlan(models.Model):
    TEST_PLAN_STATUS = (
        ('success', 'Пройдён'),
        ('in_process', 'В процессе'),
        ('failed', 'Не пройден'),
    )
    title = models.CharField(max_length=300, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    status = models.CharField(max_length=10, choices=TEST_PLAN_STATUS, default='failed', verbose_name='Статус')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    test_cases = models.ManyToManyField('test_case.TestCase', through='test_plan.PlanCase')

    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Дата обновления', auto_now=True)

    class Meta:
        verbose_name = 'Тест план'
        verbose_name_plural = 'Тест планы'

    def __str__(self):
        return self.title

    def get_absolute_url(self):

        return reverse('test_plan_view', args=[str(self.id)])


class PlanCase(models.Model):
    test_plan = models.ForeignKey(TestPlan, on_delete=models.CASCADE)
    test_case = models.ForeignKey('test_case.TestCase', on_delete=models.CASCADE)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Связь тест плана и тест кейса'
        verbose_name_plural = 'Связи тест планов и тест кейсов'


class PlanLog(models.Model):
    TEST_CASE_STATUS = (
        ('success', 'Пройдён'),
        ('failed', 'Не пройден'),
    )
    test_plan = models.ForeignKey(TestPlan, on_delete=models.CASCADE)
    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=TEST_CASE_STATUS, default='failed', verbose_name='Статус')

    class Meta:
        verbose_name = 'Лог тест-плана'
        verbose_name_plural = 'Логи тест-плана'

    def __str__(self):
        return self.created_at

modules/test_plan/forms.py
from django.forms import ModelForm
from modules.test_plan.models import TestPlan
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, ButtonHolder, Submit, Fieldset
from crispy_forms.layout import Div, HTML


class TestPlanForm(ModelForm):

    class Meta:
        model = TestPlan
        fields = ['title', 'description', ]
        helper = FormHelper()
        helper.form_method = 'POST'

    def __init__(self, *args, **kwargs):
        super(TestPlanForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.label_class = 'col-md-2 col-xs-3 text-white'
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            Div(
                Div(Field('title', css_class='form-control'), css_class='form-group'),
                Div(Field('description', css_class='form-control'), css_class='form-group'),
            Div(
                Div(
                    ButtonHolder(
                        Submit('submit', 'Сохранить', css_class='mr-3 btn-success'),
                        HTML('<a class="ml-3 btn btn-secondary" href="{% url "index" %}">Отмена</a>'),
                                 ),
                    css_class='col-12 d-flex justify-content-center'),
                css_class='form-row w-100'),
                )
                                   )

modules/test_plan/views.py
from django.shortcuts import render
from modules.test_plan.models import TestPlan
from django.views import generic
from modules.test_plan.forms import TestPlanForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


@method_decorator(login_required, name='dispatch')
class PlanListView(generic.ListView):
    model = TestPlan
    template_name = 'test_plan/test_plan_list.html'
    paginate_by = 10


@method_decorator(login_required, name='dispatch')
class DashboardView(generic.ListView):
    model = TestPlan
    template_name = 'test_plan/index.html'

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        count_all = TestPlan.objects.filter().count()
        count_success = TestPlan.objects.filter(status='success').count()
        count_fail = TestPlan.objects.filter(status='failed').count()
        context['count_all'] = count_all
        context['count_success'] = count_success
        context['count_fail'] = count_fail
        return context


@method_decorator(login_required, name='dispatch')
class PlanDetailView(generic.DetailView):
    model = TestPlan
    template_name = 'test_plan/test_plan_view.html'

    def get_context_data(self, **kwargs):
        context = super(PlanDetailView, self).get_context_data(**kwargs)
        instance = self.get_object()
        context['plancase_list'] = instance.plancase_set.filter()
        return context


@method_decorator(login_required, name='dispatch')
class PlanNewView(generic.CreateView):
    model = TestPlan
    form_class = TestPlanForm
    template_name = 'test_plan/test_plan_new.html'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        instance.save()
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class PlanUpdateView(generic.UpdateView):
    model = TestPlan
    form_class = TestPlanForm
    template_name = 'test_plan/test_plan_edit.html'

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        instance.save()
        return super().form_valid(form)

templates/test_plan/index.html
{% extends "wrapper.html" %}
{% block content %}


		<div class="container-fluid">
			<div class="section section--main">
				<div class="row">
					<div class="col-4">
						<div class="content--date">
							<span class="title title--main">Статистика тест-планов</span>
						</div>
					</div>
					<div class="col-3">
						<div class="content--date">
							<span class="title title--main">Выберите период "с"</span>
							<input type="date" class="form-control" id="date" name="date" placeholder="Дата" required>
						</div>
					</div>
					<div class="col-3">
						<div class="content--date">
							<span class="title title--main">"по"</span>
							<input type="date" class="form-control" id="date" name="date" placeholder="Дата" required>
						</div>
					</div>
					<div class="col-2">
						<div class="content--date">
							<div class="button_date">
								<button type="button" class="btn btn-secondary">Применить</button>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class=section--table>
				<div class="row ">
					<div class="col-6 ">
						<div class="table--border h-100">
							<table class="table table-sm">
								<thead>
									<tr>
										<th scope="col" style="width: 607px;">Запускалось более 1 месяца назад от выбранного периода</th>
										<th scope="col">{{ count_all }}</th>
									</tr>
								</thead>
							</table>
							<table class="table">
								<thead class="thead-light">
									<tr>
										<th scope="col">ID</th>
                                            <th scope="col">Название тест плана</th>
										<th scope="col">Дата последнего запуска</th>
										<th scope="col">Статус запуска</th>
									</tr>
								</thead>

								<tbody>
                                {% for test_plan in testplan_list %}
									<tr>
										<th scope="row">{{ test_plan.id }}</th>
										<td><a href="{% url 'test_plan_view' test_plan.pk %}">{{ test_plan.title }}</a></td>
										<td>{{ test_plan.updated_at }}</td>
										<td>{% if  test_plan.status == "failed" %}
                                            <span class="badge badge-danger "><div
                                                    class="badge--text">{{ test_plan.status }}</div></span>
                                        {% endif %}
                                        {% if  test_plan.status == "success" %}
                                            <span class="badge badge-success "><div
                                                    class="badge--text">{{ test_plan.status }}</div></span>
                                        {% endif %}
                                    {% if  test_plan.status == "in_process" %}
                                            <span class="badge badge-warning "><div
                                                    class="badge--text">{{ test_plan.status }}</div></span>
                                        {% endif %}
                                        </td>
									</tr>
                                {% endfor %}
								</tbody>
							</table>
						</div>
					</div>

					<div class="col-6">
						<div class="table--border h-100">
							<div class="table">
								<table class="table table-sm">
									<thead>
										<tr>
											<th scope="col"><span class="table--title"> Запускались за выбранный период</span></th>
											<th scope="col" ><span class="badge badge-secondary"><div class="badge--text">Всего</div></span></</th>
											<th scope="col">{{ count_all }}</th>
											<th scope="col" ><span class="badge badge-success"><div class="badge--text">Pass</div></span></</th>
											<th scope="col">{{ count_success }}</th>
											<th scope="col" ><span class="badge badge-danger"><div class="badge--text">Fail</div></span></th>
											<th scope="col">{{ count_fail }}</th>
										</tr>
									</thead>
								</table>
							</div>
							<table class="table">
								<thead class="thead-light">
									<tr>
										<th scope="col">ID</th>
										<th scope="col">Название тест плана</th>
										<th scope="col">Дата последнего запуска</th>
										<th scope="col">Статус запуска</th>
									</tr>
								</thead>
								<tbody>
                                {% for test_plan in testplan_list %}
									<tr>
										<th scope="row">{{ test_plan.id }}</th>
										<td><a href="{% url 'test_plan_view' test_plan.pk %}">{{ test_plan.title }}</a></td>
										<td>{{ test_plan.updated_at }}</td>
										<td>{% if  test_plan.status == "failed" %}
                                            <span class="badge badge-danger "><div
                                                    class="badge--text">{{ test_plan.status }}</div></span>
                                        {% endif %}
                                        {% if  test_plan.status == "success" %}
                                            <span class="badge badge-success "><div
                                                    class="badge--text">{{ test_plan.status }}</div></span>
                                        {% endif %}
                                    {% if  test_plan.status == "in_process" %}
                                            <span class="badge badge-warning "><div
                                                    class="badge--text">{{ test_plan.status }}</div></span>
                                        {% endif %}</td>
									</tr>
                                {% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>


		</div>
{% endblock %}

templates/test_plan/test_plan_edit.html
{% extends "wrapper.html" %}
{% load crispy_forms_tags %}
{% block content %}
		<div class="container-fluid">

        <div class="section section--main">
                {% if user.is_authenticated %}
				<div class="row">
                    <div class="col-5"></div>
					<div class="col-4">
						<div class="content--date">
							<span class="title title--main">Редактирование тест-плана</span>
						</div>
					</div>
                </div>
			    <div class="container">
                 {% crispy form %}
                {% csrf_token %}
			    </div>
                {% else %}
                <div class="row">
                    <div class="col-5"></div>
					<div class="col-4">
						<div class="content--date">
							<span class="title title--main">Вы не имеете доступа к этой странице. Войдите что бы продолжить</span>
						</div>
					</div>
                </div>
                {% endif %}
        <span class="text-light">Тест кейсы которые входят в этот тест план</span>
            </div>


	<div class="container">
		<div class="row">
			<div class="col-6">
				<span class="text-light">Все тест-кейсы</span>
                {% for plancase in plancase_list %}
				<div id="div1" ondrop="drop(event)" ondragover="allowDrop(event)">
					<div class="text-dark" id="drag1" draggable="true" ondragstart="drag(event)" width="336" height="69">{{ plancase.test_case.title }}</div>
				</div>
                {% endfor %}
				</div>

			<div class="col-6">
				<span class="text-light">Добавленные тест-кейсы</span>
				<div id="div2" ondrop="drop(event)" ondragover="allowDrop(event)">
					<div class="text-dark" id="drag2" draggable="true" ondragstart="drag(event)" width="336" height="69">Тест кейс 2</div>
				</div>
			</div>
		</div>
	</div>
        </div>

{% endblock %}

templates/test_plan/test_plan_list.html
{% extends "wrapper.html" %}
{% block content %}

    <div class="container-fluid">
        <div class="section section--main">
            <div class="row">
                <div class="col-4">
                    <div class="main-search">
                        <form class="form-inline my-2 my-lg-0">
                            <input class="form-control mr-sm-2" type="search" placeholder="Поиск..."
                                   aria-label="Search">
                            <button type="button" class="btn btn-secondary">Найти</button>
                        </form>
                    </div>
                </div>
                <div class="col-7">
                    <div class="main-search">
							<span class="title title--main">
								<div class="filter--container">

									<div id="accordion">
										<div class="card-header" id="headingTwo">
											<h5 class="mb-0">
												<button class="btn btn-link collapsed" data-toggle="collapse"
                                                        data-target="#collapseTwo" aria-expanded="false"
                                                        aria-controls="collapseTwo">
													<div class="text-white filter-text">
														Расширенный фильтр
													</div>
												</button>
											</h5>
										</div>
										<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo"
                                             data-parent="#accordion">
											<div class="card-body">
												<div class="row">

													<div class="col-6">
														<div class="content--date">
															<span class="title title--main">Выберите период      "с"</span>
															<input type="date" class="form-control" id="date"
                                                                   name="date" placeholder="Дата" required>
														</div>
													</div>
													<div class="col-6">
														<div class="content--date">
															<span class="title title--main">"по"</span>
															<input type="date" class="form-control" id="date"
                                                                   name="date" placeholder="Дата" required>
														</div>
													</div>
												</div>

												<div class="row">

													<div class="col-6">
														<div class="content--date">
															<span class="title title--main">Ответственный за запуск</span>
															
															<select class="btn btn-light" id="u249_input">
																<div text-white>
																<option value="Сидоров">Сидоров</option>
																<option value="Иванов">Иванов</option>
																<option value="Петров">Петров</option>
																</div>
															</select>

														</div>
													</div>
													<div class="col-6">
														<div class="content--date">
															<span class="title title--main">Результат</span>
															<select class="btn btn-light" id="u249_input">
																<option value="Сидоров">Fail</option>
																<option value="Иванов">Pass</option>
																</select>
														</div>
													</div>
												</div>

											</div>
										</div>




									</div>
								</div>
							</span>
                    </div>
                </div>

            </div>
        </div>


        <div class=section--table>
            <div class="row ">
                <div class="col-12 ">
                    <div class="table--border h-100">
                        <table class="table table-sm">
                        </table>
                        <table class="table">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Название</th>
                                <th scope="col">Дата последнего запуска</th>
                                <th scope="col">Запустил</th>
                                <th scope="col"></th>
                                <th scope="col">Всего кейсов</th>
                                <th scope="col">Выполнено</th>
                                <th scope="col">Провалено</th>
                                <th scope="col">Результат</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                            </tr>
                            </thead>


                            <tbody>

                            {% for test_plan in testplan_list %}
                                <tr>
                                    <th scope="row">{{ test_plan.id }}</th>
                                    <td><a  href="{% url 'test_plan_view' test_plan.pk %}">{{ test_plan.title }}</a></td>
                                    <td>{{ test_plan.updated_at }}</td>
                                    <td>{{ test_plan.user }}</td>
                                    <td>{{ testcase.user.image }}
                                        <i style="font-size:24px" class="fa">&#xf2c0;</i>
                                    </td>
                                    <td>12</td>
                                    <td>10</td>
                                    <td>2</td>
                                    <td>
                                        {% if  test_plan.status == "failed" %}
                                            <span class="badge badge-danger "><div
                                                    class="badge--text">{{ test_plan.status }}</div></span>
                                        {% endif %}
                                        {% if  test_plan.status == "success" %}
                                            <span class="badge badge-success "><div
                                                    class="badge--text">{{ test_plan.status }}</div></span>
                                        {% endif %}
                                    {% if  test_plan.status == "in_process" %}
                                            <span class="badge badge-warning "><div
                                                    class="badge--text">{{ test_plan.status }}</div></span>
                                        {% endif %}
                                    </td>
                                    <td>
                                        <div class="table-icon">
                                            <a href="{% url 'test_plan_edit' test_plan.pk %}">
                                                <i style="font-size:24px" class="fa">&#xf040;</i>
                                            </a>
                                        </div>
                                    </td>
                                    <td>

                                        <div class="table-icon">
                                            <a href="URL">
                                                <i style="font-size:24px" class="fa">&#xf00d;</i>
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            {% endfor %}


                            </tbody>
                        </table>
{% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Previous</a>
              {% endif %}
              <span class="page-current">
                   {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Next</a>
              {% endif %}
          </span>
      </div>
  {% endif %}


{% endblock %}
                    </div>
                </div>

            </div>
        </div>



    </div>




{% endblock %}

templates/test_plan/test_plan_new.html
{% extends "wrapper.html" %}
{% load crispy_forms_tags %}


{% block content %}
		<div class="container-fluid">
            <div class="section section--main">
                {% if user.is_authenticated %}
				<div class="row">
                    <div class="col-5"></div>
					<div class="col-4">
						<div class="content--date">
							<span class="title title--main">Создание тест-плана</span>
						</div>
					</div>
                </div>
			    <div class="container">
                 {% crispy form %}
                {% csrf_token %}
			    </div>
                {% else %}
                <div class="row">
                    <div class="col-5"></div>
					<div class="col-4">
						<div class="content--date">
							<span class="title title--main">Вы не имеете доступа к этой странице. Войдите что бы продолжить</span>
						</div>
					</div>
                </div>
                {% endif %}
            </div>
		</div>

{% endblock %}

templates/test_plan/test_plan_view.html
{% extends "wrapper.html" %}
{% block content %}


		<div class="container-fluid">
			<div class="section section--main">
				<div class="row section--title">
					<div class="col-5">
							<span class="title title--main">{{ testplan.title }}</span>
					</div>
					<div class="col-2">
							<a class="btn btn-secondary" href="{% url 'test_plan_edit' object.pk %}" role="button">Редактировать</a>
                    </div>
					<div class="col-3">
							<a class="btn btn-secondary" href="#" role="button">Запустить тест-план</a>
					</div>
					<div class="col-2">
                            <a class="btn btn-secondary" href="{% url 'test_plan_list' %}" role="button">Вернуться к списку</a>
					</div>
				</div>
                    <textarea class="test-description form-control" type="text" readonly>{{ testplan.description }}
						</textarea>
                <div class="title title--main">Лог тест-плана</div>


			<div class=section--table>
				<div class="row ">
					<div class="col-12 ">
						<div class="table--border h-100">
							<table class="table table-sm">
							</table>
							<table class="table">
								<thead class="thead-light">
									<tr>
                                        <th scope="col">Дата последнего запуска</th>
										<th scope="col">Запустил</th>
										<th scope="col"></th>
										<th scope="col">Статус</th>
										<th scope="col">Комментарий</th>
									</tr>
								</thead>

								<tbody>
									<tr>
										<td>{{ testplan.updated_at }}</td>
										<td>{{ testplan.user }}</td>
										<td>{{ testplan.user.image }}
											<i style="font-size:24px" class="fa">&#xf2c0;</i>
										</td>
										<td> {% if  testplan.status == "failed" %}
                                            <span class="badge badge-danger "><div
                                                    class="badge--text">{{ testplan.status }}</div></span>
                                        {% endif %}
                                        {% if  testplan.status == "success" %}
                                            <span class="badge badge-success "><div
                                                    class="badge--text">{{ testplan.status }}</div></span>
                                        {% endif %}
                                    {% if  testplan.status == "in_process" %}
                                            <span class="badge badge-warning "><div
                                                    class="badge--text">{{ testplan.status }}</div></span>
                                        {% endif %}</td>
                                        <td>Комментарий 1 блььалмламлал ьвльал ьмлвталтмл втлатлвтлатм амав</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>

				</div>
			</div>
                <div class="title title--main">Детали тест-плана</div>


			<div class=section--table>
				<div class="row">
					<div class="col-12 ">
						<div class="table--border h-100">
							<table class="table table-sm">
							</table>
							<table class="table">
								<thead class="thead-light">
									<tr>
                                        <th scope="col">ID</th>
										<th scope="col">Название тест-кейса</th>
                                        <th scope="col">Дата последнего запуска</th>
										<th scope="col">Запустил</th>
										<th scope="col"></th>
										<th scope="col">Статус</th>
										<th scope="col" class="comment--content">Комментарий</th>
									</tr>
								</thead>

								<tbody>
                                {% for plancase in plancase_list %}
									<tr>
                                        <th scope="row">{{ plancase.test_case.id }}</th>
										<td><a href="UrRL">{{ plancase.test_case.title }}</a></td>
										<td>{{ plancase.test_case.updated_at }}</td>
										<td>{{ plancase.test_case.user }}</td>
										<td>
                                            {{ plancase.test_case.user.image }}
											<i style="font-size:24px" class="fa">&#xf2c0;</i>
										</td>
										<td>{% if  plancase.test_case.status == "failed" %}
                                            <span class="badge badge-danger "><div
                                                    class="badge--text">{{ plancase.test_case.status }}</div></span>
                                        {% endif %}
                                        {% if  plancase.test_case.status == "success" %}
                                            <span class="badge badge-success "><div
                                                    class="badge--text">{{ plancase.test_case.status }}</div></span>
                                        {% endif %}
                                    </td>
                                        <td><div class="comment--content">{{ plancase.test_case.description }}</div></td>
									</tr>
                                {% endfor %}
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
        </div>

		</div>
{% endblock %}