modules/test_case/urls.py
from django.urls import path, re_path
from . import views
from modules.test_case.views import CaseListView, CaseDetailView

urlpatterns = [

    path('test_case_list/', CaseListView.as_view(), name='test_case_list'),
    path('test_case_new/', views.test_case_new, name='test_case_new'),
    path('test_case_edit/', views.test_case_edit, name='test_case_edit'),
    re_path(r'^test_case_view/(?P<pk>\d+)$', CaseDetailView.as_view(), name='test_case_view'),
    ]

tester/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('modules.test_plan.urls')),
    path('', include('modules.test_case.urls')),
    path('', include('modules.tag.urls')),
    path('', include('modules.profile.urls')),
    path('profile/', include('django.contrib.auth.urls')),
    ]

modules/test_case/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings


class TestCase(models.Model):
    TEST_CASE_STATUS = (
        ('success', 'Пройдён'),
        ('failed', 'Не пройден'),
    )
    title = models.CharField(max_length=300, verbose_name='Название')
    precondition = models.TextField(verbose_name='Предусловие')
    description = models.TextField(verbose_name='Описание')
    result = models.TextField(verbose_name='Результат')

    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Дата обновления', auto_now=True)
    last_run = models.DateTimeField(verbose_name='Дата последнего запуска')
    status = models.CharField(max_length=10, choices=TEST_CASE_STATUS, default='failed', verbose_name='Статус')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    tag = models.ForeignKey('tag.Tag', on_delete=models.CASCADE, verbose_name='Тег')

    class Meta:
        verbose_name = 'Тест'
        verbose_name_plural = 'Тесты'

    def __str__(self):
        return self.title


class CaseLog(models.Model):
    TEST_CASE_STATUS = (
        ('success', 'Пройдён'),
        ('failed', 'Не пройден'),
    )
    test_case = models.ForeignKey(TestCase, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=TEST_CASE_STATUS, default='failed', verbose_name='Статус')
    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)

    class Meta:
        verbose_name = 'Лог тест-кейса'
        verbose_name_plural = 'Логи тест-кейса'

    def __str__(self):
        return self.created_at

modules/test_plan/models.py
from __future__ import unicode_literals
from django.db import models
from django.conf import settings
from django.urls import reverse


class TestPlan(models.Model):
    TEST_PLAN_STATUS = (
        ('success', 'Пройдён'),
        ('in_process', 'В процессе'),
        ('failed', 'Не пройден'),
    )
    title = models.CharField(max_length=300, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    status = models.CharField(max_length=10, choices=TEST_PLAN_STATUS, default='failed', verbose_name='Статус')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    test_cases = models.ManyToManyField('test_case.TestCase', through='test_plan.PlanCase')

    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Дата обновления', auto_now=True)

    class Meta:
        verbose_name = 'Тест план'
        verbose_name_plural = 'Тест планы'

    def __str__(self):
        return self.title

    def get_absolute_url(self):

        return reverse('test_plan_view', args=[str(self.id)])


class PlanCase(models.Model):
    test_plan = models.ForeignKey(TestPlan, on_delete=models.CASCADE)
    test_case = models.ForeignKey('test_case.TestCase', on_delete=models.CASCADE)

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Связь тест плана и тест кейса'
        verbose_name_plural = 'Связи тест планов и тест кейсов'


class PlanLog(models.Model):
    TEST_CASE_STATUS = (
        ('success', 'Пройдён'),
        ('failed', 'Не пройден'),
    )
    test_plan = models.ForeignKey(TestPlan, on_delete=models.CASCADE)
    created_at = models.DateTimeField(verbose_name='Дата создания', auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    status = models.CharField(max_length=10, choices=TEST_CASE_STATUS, default='failed', verbose_name='Статус')

    class Meta:
        verbose_name = 'Лог тест-плана'
        verbose_name_plural = 'Логи тест-плана'

    def __str__(self):
        return self.created_at

modules/test_case/views.py
from django.shortcuts import render
from modules.test_case.models import TestCase
from django.views import generic
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required


@method_decorator(login_required, name='dispatch')
class CaseListView(generic.ListView):
    model = TestCase
    template_name = 'test_case/test_case_list.html'
    paginate_by = 10


@method_decorator(login_required, name='dispatch')
class CaseDetailView(generic.DetailView):
    model = TestCase
    template_name = 'test_case/test_case_view.html'

    def get_context_data(self, **kwargs):
        context = super(CaseDetailView, self).get_context_data(**kwargs)
        instance = self.get_object()
        context['plancase_list'] = instance.plancase_set.filter()
        return context


def test_case_new(request):
    return render(request, '../templates/test_case/test_case_new.html')


def test_case_edit(request):
    return render(request, '../templates/test_case/test_case_edit.html')

templates/test_case/test_case_edit.html
{% extends "wrapper.html" %}
{% block content %}

		<div class="container-fluid">
			<div class="section section--main">
				<div class="container">
				<div class="form-row align-self-center">
					<label for="inputEmail4"><span class="text-light">Название тест кейса</span></label>
					<input type="email" class="form-control" id="inputEmail4" placeholder="Имя">
				</div>
				<div class="form-group">
					<label for="inputAddress"><span class="text-light">Предусловие</span></label>
					<textarea class="test-description form-control" type="text" id="inputAddress" placeholder="Описание...">
						</textarea>
				</div>
				<div class="form-group">
					<label for="inputAddress"><span class="text-light">Описание тест кейса</span></label>
					<textarea class="test-description form-control" type="text" id="inputAddress" placeholder="Описание...">
						</textarea>
				</div>
				<div class="form-group">
					<label for="inputAddress"><span class="text-light">Результат</span></label>
					<textarea class="test-description form-control" type="text" id="inputAddress" placeholder="Описание...">
						</textarea>
				</div>
				<div class="row">

		<div class="col-2">
			<div class="content--date">
				<span class="title title--main">Теги </span>
				
				<select class="btn btn-light" id="u249_input">
					<div text-white>
					<option value="Сидоров">Тег 1</option>
					<option value="Иванов">Тег 2</option>
					<option value="Петров">Тег 3</option>
					</div>
				</select>

			</div>
		</div>
		<div class="col-2">
			<div class="content--date">
				<button type="button" class="btn btn-secondary">Добавить</button>
			</div>
		</div>
	</div>
				<div class="form-group align-items-center-around m-3  ">
				
					<button type="submit" class="btn btn-success">Сохранить</button>
					<button type="submit" class="btn btn-secondary">Отменить</button>
				</div>
			</div>
			</div>
		</div>
							


	</div>

{% endblock %}

templates/test_case/test_case_list.html
{% extends "wrapper.html" %}
{% block content %}

		<div class="container-fluid">
			<div class="section section--main">
				<div class="row">
					<div class="col-4">
						<div class="main-search">
							<form class="form-inline my-2 my-lg-0">
								<input class="form-control mr-sm-2" type="search" placeholder="Поиск..." aria-label="Search">
								<button type="button" class="btn btn-secondary">Найти</button>
							</form>
						</div>
					</div>
					<div class="col-7">
						<div class="main-search">
							<span class="title title--main">
								<div class="filter--container">

									<div id="accordion">
										<div class="card-header" id="headingTwo">
											<h5 class="mb-0">
												<button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
													<div class="text-white filter-text">
														Расширенный фильтр
													</div>
												</button>
											</h5>
										</div>
										<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
											<div class="card-body">
												<div class="row">

													<div class="col-6">
														<div class="content--date">
															<span class="title title--main">Выберите период      "с"</span>
															<input type="date" class="form-control" id="date" name="date" placeholder="Дата" required>
														</div>
													</div>
													<div class="col-6">
														<div class="content--date">
															<span class="title title--main">"по"</span>
															<input type="date" class="form-control" id="date" name="date" placeholder="Дата" required>
														</div>
													</div>
												</div>

												<div class="row">

													<div class="col-6">
														<div class="content--date">
															<span class="title title--main">Ответственный за запуск</span>
															
															<select class="btn btn-light" id="u249_input">
																<div text-white>
																<option value="Сидоров">Сидоров</option>
																<option value="Иванов">Иванов</option>
																<option value="Петров">Петров</option>
																</div>
															</select>

														</div>
													</div>
													<div class="col-6">
														<div class="content--date">
															<span class="title title--main">Результат</span>
															<select class="btn btn-light" id="u249_input">
																<option value="Сидоров">Fail</option>
																<option value="Иванов">Pass</option>
																</select>
														</div>
													</div>
													<div class="col-6">
														<div class="content--date">
															<span class="title title--main">Тест план</span>
															
															<select class="btn btn-light" id="u249_input">
																<div text-white>
																<option value="Сидоров">Первый тест-план</option>
																<option value="Иванов">Второй тест-план</option>
																<option value="Петров">Третий тест-план</option>
																</div>
															</select>

														</div>
													</div>
													<div class="col-6">
														<div class="content--date">
															<span class="title title--main">Теги</span>
															<input type="text" size="10" value="" placeholder="Введите тег...">
														</div>
													</div>
												</div>

											</div>
										</div>




									</div>
								</div>
							</span>
						</div>
					</div>

				</div>
			</div>


			<div class=section--table>
				<div class="row ">
					<div class="col-12 ">
						<div class="table--border">
							<table class="table table-sm">
							</table>
							<table class="table">
								<thead class="thead-light">
									<tr>
										<th scope="col">ID</th>
										<th scope="col">Название</th>	
										<th scope="col">Дата последнего запуска</th>
										<th scope="col">Запустил</th>
										<th scope="col"></th>
										<th scope="col">Результат запуска</th>
										<th scope="col">Входят в тест план</th>
										<th scope="col"></th>
										<th scope="col"></th>
									</tr>
								</thead>

								<tbody>
                                {% for testcase in testcase_list %}
									<tr>
										<th scope="row">{{ testcase.id }}</th>
										<td><a href="{% url 'test_case_view' testcase.pk %}">{{ testcase.title }}</a></td>
										<td>{{ testcase.updated_at }}</td>
										<td>{{ testcase.user }}</td>
										<td>{{ testcase.user.image }}
											<i style="font-size:24px" class="fa">&#xf2c0;</i>
										</td>
										<td>{% if  testcase.status == "failed" %}
                                            <span class="badge badge-danger "><div
                                                    class="badge--text">{{ testcase.status }}</div></span>
                                        {% endif %}
                                        {% if  testcase.status == "success" %}
                                            <span class="badge badge-success "><div
                                                    class="badge--text">{{ testcase.status }}</div></span>
                                        {% endif %}</td>
										<td>
											Первый тест-план
										</td>

										<td>
											<div class="table-icon">
												<a href="URL">
													<i style="font-size:24px" class="fa">&#xf040;</i>
												</a>
											</div>
										</td>
										<td>

											<div class="table-icon">
												<a href="URL">
													<i style="font-size:24px" class="fa">&#xf00d;</i>
												</a>
											</div>
										</td>
									</tr>

                                        {% endfor %}
								</tbody>
							</table>
						</div>
					</div>

				</div>
			</div>

			<div class="container-fluid">
				<div class="section section--numeration">
					<nav aria-label="Page navigation example">
						<ul class="pagination justify-content-center">
							<li class="page-item disabled">
								<a class="page-link" href="#" tabindex="-1">Previous</a>
							</li>
							<li class="page-item"><a class="page-link" href="#">1</a></li>
							<li class="page-item"><a class="page-link" href="#">2</a></li>
							<li class="page-item"><a class="page-link" href="#">3</a></li>
							<li class="page-item">
								<a class="page-link" href="#">Next</a>
							</li>
						</ul>
					</nav>
				</div>
			</div>

		</div>



{% endblock %}

templates/test_case/test_case_new.html
{% extends "wrapper.html" %}
{% block content %}


		<div class="container-fluid">
			<div class="section section--main">
			<div class="container">
				<div class="form-row align-self-center">
					<label for="inputEmail4"><span class="text-light">Название тест кейса</span></label>
					<input type="email" class="form-control" id="inputEmail4" placeholder="Имя">
				</div>
				<div class="form-group">
					<label for="inputAddress"><span class="text-light">Предусловие</span></label>
					<textarea class="test-description form-control" type="text" id="inputAddress" placeholder="Описание...">
						</textarea>
				</div>
				<div class="form-group">
					<label for="inputAddress"><span class="text-light">Описание тест кейса</span></label>
					<textarea class="test-description form-control" type="text" id="inputAddress" placeholder="Описание...">
						</textarea>
				</div>
				<div class="form-group">
					<label for="inputAddress"><span class="text-light">Результат</span></label>
					<textarea class="test-description form-control" type="text" id="inputAddress" placeholder="Описание...">
						</textarea>
				</div>
				<div class="form-group align-items-center">
				
					<button type="submit" class="btn btn-success">Сохранить</button>
					<button type="submit" class="btn btn-secondary">Отменить</button>
				</div>
			</div>
		</div>
		</div>
			</div>
		</div>
	</div>

{% endblock %}

templates/test_case/test_case_view.html
{% extends "wrapper.html" %}
{% block content %}


		<div class="container-fluid">
			<div class="section section--main">
				<div class="row section--title">
					<div class="col-6">
							<span class="title title--main">{{ testcase.title }}</span>
					</div>
					<div class="col-3">
                            <a class="btn btn-secondary" href="{% url 'test_case_edit' %}" role="button">Редактировать</a>
                    </div>

					<div class="col-3">
                           <a class="btn btn-secondary" href="{% url 'test_case_list' %}" role="button">Вернуться к списку</a>
					</div>
                </div>
                <div class="title title--main">Предусловие</div>
                <textarea class="test-description form-control" type="text" readonly>{{ testcase.precondition }}</textarea>
                <div class="title title--main">Описание</div>
                <textarea class="test-description form-control" type="text" readonly>{{ testcase.description }}</textarea>
                <div class="title title--main">Ожидаемый результат</div>
                <textarea class="test-description form-control" type="text" readonly>{{ testcase.result }}</textarea>

                <div class="title title--main">Тест план</div>
                {% for plancase in plancase_list %}
                <a href="URL" class="text-third">{{ plancase.test_plan.title }}</a>,
                {% endfor %}
                  <div class="title title--main">Тег</div>
                <a href="URL" class="text-third">{{ testcase.tag }}</a>

                <div class="title title--main">Лог тест-кейса</div>


			<div class=section--table>
				<div class="row ">
					<div class="col-12 ">
						<div class="table--border h-100">
							<table class="table table-sm">
							</table>
							<table class="table">
								<thead class="thead-light">
									<tr>
                                        <th scope="col">Дата последнего запуска</th>
										<th scope="col">Запустил</th>
										<th scope="col"></th>
										<th scope="col">Статус</th>
										<th scope="col">Комментарий</th>
									</tr>
								</thead>

								<tbody>
									<tr>
										<td>{{ testcase.updated_at }}</td>
										<td>{{ testcase.user }}</td>
										<td>
											<i style="font-size:24px" class="fa">&#xf2c0;</i>
										</td>
										<td>{% if  testcase.status == "failed" %}
                                            <span class="badge badge-danger "><div
                                                    class="badge--text">{{ testcase.status }}</div></span>
                                        {% endif %}
                                        {% if  testcase.status == "success" %}
                                            <span class="badge badge-success "><div
                                                    class="badge--text">{{ testcase.status }}</div></span>
                                        {% endif %}</td>
                                        <td>{{ testcase.description }}</td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>

				</div>
			</div>



        </div>

		</div>
{% endblock %}